train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/data/DIV2K/train/HR
      meta_info_file: ./data/meta_info/DIV2K_train_INR.txt
      repeat: 40 # 20 for bz 16
      cache: bin
  wrapper:
    name: sr-implicit-downsampled-cascaded
    args:
      inp_size: 48
      batch_size: 32
      scale_min: [1]
      scale_max: [8]
      sample_q: 2304
      augment: True
      phase: train
      k: 1

  batch_size: 32

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/data/DIV2K/val/HR
      first_k: 10
      repeat: 40
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-cascaded
    args:
      inp_size: 48
      batch_size: 8
      scale_min: [1]
      scale_max: [8]
      sample_q: 2304
      phase: valid

  batch_size: 8

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: amsit
  args:
    base_dim: 256
    head: 8
    r: 3
    imnet_num: 1
    conv_num: 1
    is_cell: True
    local_attn: True
    use_lem: True
    MsC_heads: 16
    MsSA_q: 4


    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: True

    pb_spec:
      name: posenc
      args:
        posenc_type: 'sinusoid'
        posenc_scale: 10
        hidden_dims: 64
        enc_dims: 64
        gamma: 1

    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256,256,256,256]
        act: 'gelu'

optimizer:
  name: adam
  args:
    lr: 1.e-5

epoch_max: 1050

warmup_step_lr:
  multiplier: 10
  total_epoch: 50

#multi_step_lr:
#  milestones: [200, 400, 600, 800]
#  gamma: 0.5

epoch_val: 50
epoch_save: 50

resume: ~
pre_train: #Please load the AMSIT weights!
